name = "ollama_gleam"
version = "0.0.2"

description = "A client for Ollama"
licences = ["Apache-2.0"]
repository = { type = "github", user = "ddanielsantos", repo = "ollama_gleam" }
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
